### ISSUE TITLE
How to link Images

### ISSUE THREAD

**Issue by Hatzen** [LucasFsc/Html2Pdf#2]
I want to use your awesome lib to create pdf from an html file within my assets folder. This html file should contain a image also stored within the assets folder, do you think this is possible?   
I know i got this working by displaying the content in a webview and printing it. But that would force me to print the webview and cant be done in a background process..

**Comment by boldijar** [comment]
You can add the image as base64 in the html and it will work

Example:
`<div>
  <p>Taken from wikpedia</p>
  <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
</div>`
