### ISSUE TITLE
Opening the file after pdf generation

### ISSUE THREAD

**Issue by FrancescoBonizzi** [LucasFsc/Html2Pdf#4]
Hi and thanks for your work! It's awesome!
I have a question. 

To generate the PDF I do (inside an Activity):

```
    val converter = Html2Pdf.Companion.Builder()
        .context(this)
        .html( assets.open("test.html").bufferedReader().use {it.readText()})
        .file(File("${this.filesDir}/test.pdf"))
        .build()
    converter.convertToPdf(this)
```

Then, on success, I use this code to open the file with the default app:

```
    override fun onSuccess() {
        val intent = Intent(Intent.ACTION_VIEW)
        intent.setDataAndType(Uri.parse("${this.filesDir}/test.pdf"), MimeTypeMap.getSingleton().getMimeTypeFromExtension(".pdf"))
        startActivity(intent)
    }
```

The call itself doens't throw any exception, but nothing happens and I see from the logs this:

`E/fdsan: failed to exchange ownership of file descriptor: fd 61 is owned by ParcelFileDescriptor 0xe0fea7a, was expected to be unowned`.

What am I doing wrong, according to you?

Thanks!

**Comment by Hatzen** [comment]
i cannot see a concrete issue with your code, maybe it is an permission issue. Or the file stream is not called within the onSuccess callback, i didnt test at that moment. 
For me this is working: 

```
    private fun openPdf(file: File) {
        val target = Intent(Intent.ACTION_VIEW)
        target.setDataAndType(Uri.fromFile(file), "application/pdf")
        target.flags = Intent.FLAG_ACTIVITY_NO_HISTORY

        val intent = Intent.createChooser(target, "Open File")
        try {
            startActivity(intent)
        } catch (e: ActivityNotFoundException) {
            // Instruct the user to install a PDF reader here, or something
        }
    }
```
an excerpt of my repo where i use this lib. https://github.com/Hatzen/BusinessPdfs/blob/master/app/src/main/java/de/hartz/software/businesspdfs/MainActivity.kt#L150

**Comment by FrancescoBonizzi** [comment]
Thanks! It works!
